version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta padrão do RabbitMQ para mensagens
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - web_api_metrics_network
  api-schedule:
    build:
      context: ./ScheduleService
      dockerfile: Dockerfile
      args:
        version: 1
    image: api-schedule
    ports:
      - 8080:8080
    networks:
      - web_api_metrics_network
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
  consumer-user:
    build:
      context: ./UserConsumer
      dockerfile: Dockerfile
      args:
        version: 1
    image: consumer-user
    ports:
      - 6060:6060
    networks:
      - web_api_metrics_network
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest  

networks:
  web_api_metrics_network:
    driver: overlay
    attachable: true